import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'business_model.freezed.dart';
part 'business_model.g.dart';

@freezed
class BusinessModel with _$BusinessModel {
  const factory BusinessModel({
    @JsonKey(name: 'id')
    required int id, // Non-nullable, will be generated by database
    @JsonKey(name: 'business_name') required String businessName,
    required String email,
    @JsonKey(name: 'image_url') String? imageUrl,
    required double latitude,
    required double longitude,
    @JsonKey(name: 'user_email') required String userEmail,
    @JsonKey(name: 'created_at') DateTime? createdAt,
    @JsonKey(name: 'is_verified') @Default(false) bool isVerified,
    String? category, // Added category field
  }) = _BusinessModel;

  factory BusinessModel.fromJson(Map<String, dynamic> json) =>
      _$BusinessModelFromJson(json);

  // Factory method to create a model without an ID (for initial creation)
  factory BusinessModel.create({
    required String businessName,
    required String email,
    String? imageUrl,
    required double latitude,
    required double longitude,
    required String userEmail,
    bool isVerified = false,
    String? category, // Added category parameter
  }) =>
      BusinessModel(
        id: 0, // Placeholder, will be replaced by database
        businessName: businessName,
        email: email,
        imageUrl: imageUrl,
        latitude: latitude,
        longitude: longitude,
        userEmail: userEmail,
        isVerified: isVerified,
        category: category, // Added category
      );
}
